# Generated by Django 4.2.2 on 2023-09-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0004_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
